public class Test {
    
 /*   public class results{
        public final string gender;
        public 
    }
    
    public class nameclass{
        public final string title;
        public final string first;
        public final string last;
        
        public name(string title,string first,string last){
            this.title=title;
            this.first=first;
            this.last=last;
        }
       
    }
        
        
        
    } */
    
    
    
}